"""Reject mismatched synthetic headers before any pixel decoding."""

from dataclasses import replace
import io
from tempfile import TemporaryDirectory
import unittest
from unittest.mock import patch

from PIL import Image

from paramguard.evidence import EvidenceArtifact, EvidenceRole
from paramguard.image_quality import (
    ImageQualityConfig,
    ImageQualityFlag,
    assess_image_quality_bytes,
)
from paramguard.ocr import TesseractOcrEngine
from paramguard.routing import RouteReason
from paramguard.synthetic import default_clean_case, render_case
from paramguard.template import SYNTHETIC_PANEL_TEMPLATE
from paramguard.vision_pipeline import (
    VisionPipelineBindingError,
    build_tesseract_pipeline_spec,
    run_gated_ocr_pair,
)
from paramguard.workflow import AiVerdict, ReviewState, ReviewTask
from tests.test_vision_pipeline import FakeRunner, complete_and_start_human_first


def pgm_header(width: int, height: int) -> bytes:
    # Deliberately no pixels: reading the size needs only these generated bytes.
    return f"P5\n{width} {height}\n255\n".encode("ascii")


class ImagePreflightTests(unittest.TestCase):
    def test_header_mismatch_rejects_before_load_and_leaves_metrics_unmeasured(
        self,
    ) -> None:
        template = SYNTHETIC_PANEL_TEMPLATE
        sizes = (
            (template.width + 1, template.height),
            (template.width, template.height + 1),
            (10_000, 8_000),
        )
        for width, height in sizes:
            with self.subTest(size=(width, height)):
                with patch(
                    "PIL.PpmImagePlugin.PpmImageFile.load",
                    side_effect=AssertionError("mismatched pixels must not decode"),
                ) as load:
                    result = assess_image_quality_bytes(
                        pgm_header(width, height), template=template
                    )
                load.assert_not_called()
                self.assertEqual((result.width, result.height), (width, height))
                self.assertEqual(result.flags, (ImageQualityFlag.DIMENSION_MISMATCH,))
                self.assertIsNone(result.contrast_stddev)
                self.assertIsNone(result.edge_variance)
                self.assertFalse(result.acceptable_for_ocr)

    def test_small_valid_wrong_size_png_is_not_converted(self) -> None:
        with io.BytesIO() as buffer:
            Image.new("RGB", (2, 2), "white").save(buffer, format="PNG")
            content = buffer.getvalue()
        with patch(
            "PIL.Image.Image.convert",
            side_effect=AssertionError("mismatched pixels must not convert"),
        ) as convert:
            result = assess_image_quality_bytes(
                content, template=SYNTHETIC_PANEL_TEMPLATE
            )
        convert.assert_not_called()
        self.assertEqual(result.flags, (ImageQualityFlag.DIMENSION_MISMATCH,))
        self.assertIsNone(result.contrast_stddev)
        self.assertIsNone(result.edge_variance)

    def test_zero_heuristic_thresholds_do_not_bypass_dimension_rejection(
        self,
    ) -> None:
        config = ImageQualityConfig(minimum_contrast_stddev=0, minimum_edge_variance=0)
        with patch(
            "PIL.PpmImagePlugin.PpmImageFile.load",
            side_effect=AssertionError("mismatched pixels must not decode"),
        ):
            result = assess_image_quality_bytes(
                pgm_header(2, 2), template=SYNTHETIC_PANEL_TEMPLATE, config=config
            )
        self.assertFalse(result.acceptable_for_ocr)
        self.assertEqual(result.flags, (ImageQualityFlag.DIMENSION_MISMATCH,))
        self.assertEqual(result.config_sha256, config.content_sha256)

    def test_matching_image_retains_actual_measurements(self) -> None:
        with TemporaryDirectory() as directory:
            rendered = render_case(default_clean_case(), output_root=directory)
            result = assess_image_quality_bytes(
                rendered.left_image_path.read_bytes(),
                template=SYNTHETIC_PANEL_TEMPLATE,
            )
        self.assertTrue(result.acceptable_for_ocr)
        self.assertIs(type(result.contrast_stddev), float)
        self.assertIs(type(result.edge_variance), float)
        self.assertGreater(result.contrast_stddev, 0)
        self.assertGreater(result.edge_variance, 0)

    def test_locked_mismatched_side_abstains_without_ocr_or_human_changes(
        self,
    ) -> None:
        for side in (EvidenceRole.LEFT_PHOTO, EvidenceRole.RIGHT_SCREENSHOT):
            with self.subTest(side=side), TemporaryDirectory() as directory:
                rendered = render_case(default_clean_case(), output_root=directory)
                content = pgm_header(1201, 620)
                bad_path = (
                    rendered.left_image_path
                    if side is EvidenceRole.LEFT_PHOTO
                    else rendered.right_image_path
                )
                bad_path.write_bytes(content)
                manifest = replace(
                    rendered.manifest,
                    artifacts=tuple(
                        EvidenceArtifact.from_bytes(
                            artifact_id=item.artifact_id,
                            role=item.role,
                            content=content,
                            media_type="image/x-portable-graymap",
                        )
                        if item.role is side
                        else item
                        for item in rendered.manifest.artifacts
                    ),
                )
                runner = FakeRunner()
                engine = TesseractOcrEngine(binary="python3", runner=runner)
                task = ReviewTask(
                    task_id="dimension-preflight",
                    evidence_manifest=manifest,
                    approved_pipeline_spec=build_tesseract_pipeline_spec(
                        engine=engine, template=SYNTHETIC_PANEL_TEMPLATE
                    ),
                    reviewer_id="primary-reviewer",
                )
                complete_and_start_human_first(task)
                human_before = task.human_decisions()
                with patch(
                    "PIL.PpmImagePlugin.PpmImageFile.load",
                    side_effect=AssertionError("mismatched pixels must not decode"),
                ) as load:
                    outcome = run_gated_ocr_pair(
                        task,
                        run_id="run-001",
                        left_image_path=rendered.left_image_path,
                        right_image_path=rendered.right_image_path,
                        engine=engine,
                        template=SYNTHETIC_PANEL_TEMPLATE,
                    )
                load.assert_not_called()
                bad_quality = (
                    outcome.left_quality
                    if side is EvidenceRole.LEFT_PHOTO
                    else outcome.right_quality
                )
                self.assertIsNone(bad_quality.contrast_stddev)
                self.assertEqual(outcome.left_ocr, ())
                self.assertEqual(outcome.right_ocr, ())
                self.assertEqual(task.state, ReviewState.AI_REVIEW_COMPLETE)
                self.assertEqual(task.human_decisions(), human_before)
                self.assertEqual(len(outcome.ai_assessments), 4)
                self.assertTrue(
                    all(
                        item.verdict is AiVerdict.UNABLE_TO_JUDGE
                        for item in outcome.ai_assessments
                    )
                )
                self.assertTrue(
                    all(
                        RouteReason.UNREADABLE_IMAGE in item.reasons
                        and not item.automatic_release_allowed
                        for item in outcome.routing
                    )
                )
                self.assertFalse(any("tsv" in call for call in runner.commands))

    def test_pre_header_gate_pipeline_is_rejected_before_source_reads(self) -> None:
        with TemporaryDirectory() as directory:
            rendered = render_case(default_clean_case(), output_root=directory)
            runner = FakeRunner()
            engine = TesseractOcrEngine(binary="python3", runner=runner)
            current = build_tesseract_pipeline_spec(
                engine=engine, template=SYNTHETIC_PANEL_TEMPLATE
            )
            task = ReviewTask(
                task_id="pre-header-gate",
                evidence_manifest=rendered.manifest,
                approved_pipeline_spec=replace(current, pipeline_version="1.4"),
                reviewer_id="primary-reviewer",
            )
            complete_and_start_human_first(task)
            human_before = task.human_decisions()
            with patch(
                "paramguard.vision_pipeline.Path.open",
                side_effect=AssertionError("old pipeline must not read images"),
            ) as read:
                with self.assertRaises(VisionPipelineBindingError):
                    run_gated_ocr_pair(
                        task,
                        run_id="run-001",
                        left_image_path=rendered.left_image_path,
                        right_image_path=rendered.right_image_path,
                        engine=engine,
                        template=SYNTHETIC_PANEL_TEMPLATE,
                    )
                read.assert_not_called()
            self.assertEqual(task.human_decisions(), human_before)
            self.assertEqual(task._ai_results, {})
            self.assertFalse(any("tsv" in call for call in runner.commands))


if __name__ == "__main__":
    unittest.main()
